#!/bin/bash

################### Check for and install dependencies ###############

clear

if which cowsay >/dev/null; then
echo " "
else
echo "....There seem to be some unmet dependencies... please enter your password..."
    echo " This only needs doing once! "
    sudo apt-get install -y -qq cowsay 
fi

clear

######################## Start UI ###################################

while true; do
	cowsay "let's steal some videos!"
	sleep 3
	clear 
cowsay "Would you like to get video from iPlayer (1) or youtube? (2)"  
 read yn
    case $yn in
###################################################################       
 	[1]* ) chmod +x iplayer_module; exec ./iplayer_module; exit ;;
       
##################################################################
 	[2]* ) chmod +x youtube_module; exec ./youtube_module; exit ;;
        * ) echo "Please answer 1 or 2.";;
    esac
done

